# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sym/models/resource.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sym.enums import service_pb2 as sym_dot_enums_dot_service__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sym/models/resource.proto',
  package='sym.models',
  syntax='proto3',
  serialized_options=b'Z#github.com/symopsio/types/go/models',
  serialized_pb=b'\n\x19sym/models/resource.proto\x12\nsym.models\x1a\x17sym/enums/service.proto\";\n\x08Resource\x12#\n\x07service\x18\x01 \x01(\x0e\x32\x12.sym.enums.Service\x12\n\n\x02id\x18\x02 \x01(\tB%Z#github.com/symopsio/types/go/modelsb\x06proto3'
  ,
  dependencies=[sym_dot_enums_dot_service__pb2.DESCRIPTOR,])




_RESOURCE = _descriptor.Descriptor(
  name='Resource',
  full_name='sym.models.Resource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service', full_name='sym.models.Resource.service', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='sym.models.Resource.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=125,
)

_RESOURCE.fields_by_name['service'].enum_type = sym_dot_enums_dot_service__pb2._SERVICE
DESCRIPTOR.message_types_by_name['Resource'] = _RESOURCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Resource = _reflection.GeneratedProtocolMessageType('Resource', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCE,
  '__module__' : 'sym.models.resource_pb2'
  # @@protoc_insertion_point(class_scope:sym.models.Resource)
  })
_sym_db.RegisterMessage(Resource)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
