# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sym/models/schema.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sym/models/schema.proto',
  package='sym.models',
  syntax='proto3',
  serialized_options=b'Z#github.com/symopsio/types/go/models',
  serialized_pb=b'\n\x17sym/models/schema.proto\x12\nsym.models\"\x19\n\x06Schema\x12\x0f\n\x07version\x18\x01 \x01(\x05\x42%Z#github.com/symopsio/types/go/modelsb\x06proto3'
)




_SCHEMA = _descriptor.Descriptor(
  name='Schema',
  full_name='sym.models.Schema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='sym.models.Schema.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=64,
)

DESCRIPTOR.message_types_by_name['Schema'] = _SCHEMA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Schema = _reflection.GeneratedProtocolMessageType('Schema', (_message.Message,), {
  'DESCRIPTOR' : _SCHEMA,
  '__module__' : 'sym.models.schema_pb2'
  # @@protoc_insertion_point(class_scope:sym.models.Schema)
  })
_sym_db.RegisterMessage(Schema)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
