# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sym/models/uuid.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sym/models/uuid.proto',
  package='sym.models',
  syntax='proto3',
  serialized_options=b'Z#github.com/symopsio/types/go/models',
  serialized_pb=b'\n\x15sym/models/uuid.proto\x12\nsym.models\"\x15\n\x04UUID\x12\r\n\x05value\x18\x01 \x01(\tB%Z#github.com/symopsio/types/go/modelsb\x06proto3'
)




_UUID = _descriptor.Descriptor(
  name='UUID',
  full_name='sym.models.UUID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='sym.models.UUID.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['UUID'] = _UUID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UUID = _reflection.GeneratedProtocolMessageType('UUID', (_message.Message,), {
  'DESCRIPTOR' : _UUID,
  '__module__' : 'sym.models.uuid_pb2'
  # @@protoc_insertion_point(class_scope:sym.models.UUID)
  })
_sym_db.RegisterMessage(UUID)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
