# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sym/enums/service.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sym/enums/service.proto',
  package='sym.enums',
  syntax='proto3',
  serialized_options=b'Z\"github.com/symopsio/types/go/enums',
  serialized_pb=b'\n\x17sym/enums/service.proto\x12\tsym.enums*@\n\x07Service\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05SLACK\x10\x01\x12\x08\n\x04OKTA\x10\x02\x12\x07\n\x03\x41WS\x10\x03\x12\n\n\x06\x43USTOM\x10\x04\x42$Z\"github.com/symopsio/types/go/enumsb\x06proto3'
)

_SERVICE = _descriptor.EnumDescriptor(
  name='Service',
  full_name='sym.enums.Service',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SLACK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OKTA', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AWS', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUSTOM', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=38,
  serialized_end=102,
)
_sym_db.RegisterEnumDescriptor(_SERVICE)

Service = enum_type_wrapper.EnumTypeWrapper(_SERVICE)
UNKNOWN = 0
SLACK = 1
OKTA = 2
AWS = 3
CUSTOM = 4


DESCRIPTOR.enum_types_by_name['Service'] = _SERVICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
