# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sym/messages/authz.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sym.models import schema_pb2 as sym_dot_models_dot_schema__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sym/messages/authz.proto',
  package='sym.messages',
  syntax='proto3',
  serialized_options=b'Z%github.com/symopsio/types/go/messages',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18sym/messages/authz.proto\x12\x0csym.messages\x1a\x17sym/models/schema.proto\"G\n\x05\x41uthz\x12\"\n\x06schema\x18\x01 \x01(\x0b\x32\x12.sym.models.Schema\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"1\n\rAuthzResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x14\n\x0c\x65rrorMessage\x18\x02 \x01(\tB\'Z%github.com/symopsio/types/go/messagesb\x06proto3'
  ,
  dependencies=[sym_dot_models_dot_schema__pb2.DESCRIPTOR,])




_AUTHZ = _descriptor.Descriptor(
  name='Authz',
  full_name='sym.messages.Authz',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='schema', full_name='sym.messages.Authz.schema', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user', full_name='sym.messages.Authz.user', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='role', full_name='sym.messages.Authz.role', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=138,
)


_AUTHZRESPONSE = _descriptor.Descriptor(
  name='AuthzResponse',
  full_name='sym.messages.AuthzResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='sym.messages.AuthzResponse.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errorMessage', full_name='sym.messages.AuthzResponse.errorMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=189,
)

_AUTHZ.fields_by_name['schema'].message_type = sym_dot_models_dot_schema__pb2._SCHEMA
DESCRIPTOR.message_types_by_name['Authz'] = _AUTHZ
DESCRIPTOR.message_types_by_name['AuthzResponse'] = _AUTHZRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Authz = _reflection.GeneratedProtocolMessageType('Authz', (_message.Message,), {
  'DESCRIPTOR' : _AUTHZ,
  '__module__' : 'sym.messages.authz_pb2'
  # @@protoc_insertion_point(class_scope:sym.messages.Authz)
  })
_sym_db.RegisterMessage(Authz)

AuthzResponse = _reflection.GeneratedProtocolMessageType('AuthzResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUTHZRESPONSE,
  '__module__' : 'sym.messages.authz_pb2'
  # @@protoc_insertion_point(class_scope:sym.messages.AuthzResponse)
  })
_sym_db.RegisterMessage(AuthzResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
