# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sym/messages/dispatch.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sym/messages/dispatch.proto',
  package='sym.messages',
  syntax='proto3',
  serialized_options=b'Z%github.com/symopsio/types/go/messages',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bsym/messages/dispatch.proto\x12\x0csym.messages\x1a\x19google/protobuf/any.proto\"A\n\x08\x44ispatch\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12%\n\x07payload\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyB\'Z%github.com/symopsio/types/go/messagesb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_DISPATCH = _descriptor.Descriptor(
  name='Dispatch',
  full_name='sym.messages.Dispatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='sym.messages.Dispatch.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='sym.messages.Dispatch.payload', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=137,
)

_DISPATCH.fields_by_name['payload'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['Dispatch'] = _DISPATCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Dispatch = _reflection.GeneratedProtocolMessageType('Dispatch', (_message.Message,), {
  'DESCRIPTOR' : _DISPATCH,
  '__module__' : 'sym.messages.dispatch_pb2'
  # @@protoc_insertion_point(class_scope:sym.messages.Dispatch)
  })
_sym_db.RegisterMessage(Dispatch)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
