# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sym/messages/expiration.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sym.models import resource_pb2 as sym_dot_models_dot_resource__pb2
from sym.models import schema_pb2 as sym_dot_models_dot_schema__pb2
from sym.models import user_pb2 as sym_dot_models_dot_user__pb2
from sym.models import uuid_pb2 as sym_dot_models_dot_uuid__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sym/messages/expiration.proto',
  package='sym.messages',
  syntax='proto3',
  serialized_options=b'Z%github.com/symopsio/types/go/messages',
  serialized_pb=b'\n\x1dsym/messages/expiration.proto\x12\x0csym.messages\x1a\x19sym/models/resource.proto\x1a\x17sym/models/schema.proto\x1a\x15sym/models/user.proto\x1a\x15sym/models/uuid.proto\"\xd1\x01\n\nExpiration\x12\x1c\n\x02id\x18\x01 \x01(\x0b\x32\x10.sym.models.UUID\x12\"\n\x06schema\x18\x02 \x01(\x0b\x32\x12.sym.models.Schema\x12/\n\x06target\x18\x03 \x01(\x0b\x32\x1f.sym.messages.Expiration.Target\x1aP\n\x06Target\x12\x1e\n\x04user\x18\x01 \x01(\x0b\x32\x10.sym.models.User\x12&\n\x08resource\x18\x02 \x01(\x0b\x32\x14.sym.models.ResourceB\'Z%github.com/symopsio/types/go/messagesb\x06proto3'
  ,
  dependencies=[sym_dot_models_dot_resource__pb2.DESCRIPTOR,sym_dot_models_dot_schema__pb2.DESCRIPTOR,sym_dot_models_dot_user__pb2.DESCRIPTOR,sym_dot_models_dot_uuid__pb2.DESCRIPTOR,])




_EXPIRATION_TARGET = _descriptor.Descriptor(
  name='Target',
  full_name='sym.messages.Expiration.Target',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='sym.messages.Expiration.Target.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resource', full_name='sym.messages.Expiration.Target.resource', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=355,
)

_EXPIRATION = _descriptor.Descriptor(
  name='Expiration',
  full_name='sym.messages.Expiration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sym.messages.Expiration.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schema', full_name='sym.messages.Expiration.schema', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='sym.messages.Expiration.target', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_EXPIRATION_TARGET, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=355,
)

_EXPIRATION_TARGET.fields_by_name['user'].message_type = sym_dot_models_dot_user__pb2._USER
_EXPIRATION_TARGET.fields_by_name['resource'].message_type = sym_dot_models_dot_resource__pb2._RESOURCE
_EXPIRATION_TARGET.containing_type = _EXPIRATION
_EXPIRATION.fields_by_name['id'].message_type = sym_dot_models_dot_uuid__pb2._UUID
_EXPIRATION.fields_by_name['schema'].message_type = sym_dot_models_dot_schema__pb2._SCHEMA
_EXPIRATION.fields_by_name['target'].message_type = _EXPIRATION_TARGET
DESCRIPTOR.message_types_by_name['Expiration'] = _EXPIRATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Expiration = _reflection.GeneratedProtocolMessageType('Expiration', (_message.Message,), {

  'Target' : _reflection.GeneratedProtocolMessageType('Target', (_message.Message,), {
    'DESCRIPTOR' : _EXPIRATION_TARGET,
    '__module__' : 'sym.messages.expiration_pb2'
    # @@protoc_insertion_point(class_scope:sym.messages.Expiration.Target)
    })
  ,
  'DESCRIPTOR' : _EXPIRATION,
  '__module__' : 'sym.messages.expiration_pb2'
  # @@protoc_insertion_point(class_scope:sym.messages.Expiration)
  })
_sym_db.RegisterMessage(Expiration)
_sym_db.RegisterMessage(Expiration.Target)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
