# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sym/messages/options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sym.enums import service_pb2 as sym_dot_enums_dot_service__pb2
from sym.models import schema_pb2 as sym_dot_models_dot_schema__pb2
from sym.models import user_pb2 as sym_dot_models_dot_user__pb2
from sym.models import uuid_pb2 as sym_dot_models_dot_uuid__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sym/messages/options.proto',
  package='sym.messages',
  syntax='proto3',
  serialized_options=b'Z%github.com/symopsio/types/go/messages',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1asym/messages/options.proto\x12\x0csym.messages\x1a\x17sym/enums/service.proto\x1a\x17sym/models/schema.proto\x1a\x15sym/models/user.proto\x1a\x15sym/models/uuid.proto\"\xde\x01\n\x07Options\x12\x1c\n\x02id\x18\x01 \x01(\x0b\x32\x10.sym.models.UUID\x12\"\n\x06schema\x18\x02 \x01(\x0b\x32\x12.sym.models.Schema\x12#\n\trequester\x18\x03 \x01(\x0b\x32\x10.sym.models.User\x12,\n\x06\x66ilter\x18\x04 \x01(\x0b\x32\x1c.sym.messages.Options.Filter\x1a>\n\x06\x46ilter\x12#\n\x07service\x18\x01 \x01(\x0e\x32\x12.sym.enums.Service\x12\x0f\n\x07pattern\x18\x02 \x01(\t\"=\n\x0fOptionsResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x0f\n\x07options\x18\x03 \x03(\tB\'Z%github.com/symopsio/types/go/messagesb\x06proto3'
  ,
  dependencies=[sym_dot_enums_dot_service__pb2.DESCRIPTOR,sym_dot_models_dot_schema__pb2.DESCRIPTOR,sym_dot_models_dot_user__pb2.DESCRIPTOR,sym_dot_models_dot_uuid__pb2.DESCRIPTOR,])




_OPTIONS_FILTER = _descriptor.Descriptor(
  name='Filter',
  full_name='sym.messages.Options.Filter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='service', full_name='sym.messages.Options.Filter.service', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pattern', full_name='sym.messages.Options.Filter.pattern', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=363,
)

_OPTIONS = _descriptor.Descriptor(
  name='Options',
  full_name='sym.messages.Options',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sym.messages.Options.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='schema', full_name='sym.messages.Options.schema', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requester', full_name='sym.messages.Options.requester', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter', full_name='sym.messages.Options.filter', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_OPTIONS_FILTER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=363,
)


_OPTIONSRESPONSE = _descriptor.Descriptor(
  name='OptionsResponse',
  full_name='sym.messages.OptionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='sym.messages.OptionsResponse.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='sym.messages.OptionsResponse.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='options', full_name='sym.messages.OptionsResponse.options', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=426,
)

_OPTIONS_FILTER.fields_by_name['service'].enum_type = sym_dot_enums_dot_service__pb2._SERVICE
_OPTIONS_FILTER.containing_type = _OPTIONS
_OPTIONS.fields_by_name['id'].message_type = sym_dot_models_dot_uuid__pb2._UUID
_OPTIONS.fields_by_name['schema'].message_type = sym_dot_models_dot_schema__pb2._SCHEMA
_OPTIONS.fields_by_name['requester'].message_type = sym_dot_models_dot_user__pb2._USER
_OPTIONS.fields_by_name['filter'].message_type = _OPTIONS_FILTER
DESCRIPTOR.message_types_by_name['Options'] = _OPTIONS
DESCRIPTOR.message_types_by_name['OptionsResponse'] = _OPTIONSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Options = _reflection.GeneratedProtocolMessageType('Options', (_message.Message,), {

  'Filter' : _reflection.GeneratedProtocolMessageType('Filter', (_message.Message,), {
    'DESCRIPTOR' : _OPTIONS_FILTER,
    '__module__' : 'sym.messages.options_pb2'
    # @@protoc_insertion_point(class_scope:sym.messages.Options.Filter)
    })
  ,
  'DESCRIPTOR' : _OPTIONS,
  '__module__' : 'sym.messages.options_pb2'
  # @@protoc_insertion_point(class_scope:sym.messages.Options)
  })
_sym_db.RegisterMessage(Options)
_sym_db.RegisterMessage(Options.Filter)

OptionsResponse = _reflection.GeneratedProtocolMessageType('OptionsResponse', (_message.Message,), {
  'DESCRIPTOR' : _OPTIONSRESPONSE,
  '__module__' : 'sym.messages.options_pb2'
  # @@protoc_insertion_point(class_scope:sym.messages.OptionsResponse)
  })
_sym_db.RegisterMessage(OptionsResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
