// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: sym/messages/approval.proto

package messages

import (
	proto "github.com/golang/protobuf/proto"
	models "github.com/symopsio/types/go/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Approval messages represent approval for a target user to use a resource
type Approval struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *models.UUID   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Schema  *models.Schema `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Request *Request       `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Meta    *Approval_Meta `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *Approval) Reset() {
	*x = Approval{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sym_messages_approval_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Approval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Approval) ProtoMessage() {}

func (x *Approval) ProtoReflect() protoreflect.Message {
	mi := &file_sym_messages_approval_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Approval.ProtoReflect.Descriptor instead.
func (*Approval) Descriptor() ([]byte, []int) {
	return file_sym_messages_approval_proto_rawDescGZIP(), []int{0}
}

func (x *Approval) GetId() *models.UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Approval) GetSchema() *models.Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Approval) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Approval) GetMeta() *Approval_Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Approval_Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Approver *models.User `protobuf:"bytes,1,opt,name=approver,proto3" json:"approver,omitempty"`
}

func (x *Approval_Meta) Reset() {
	*x = Approval_Meta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sym_messages_approval_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Approval_Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Approval_Meta) ProtoMessage() {}

func (x *Approval_Meta) ProtoReflect() protoreflect.Message {
	mi := &file_sym_messages_approval_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Approval_Meta.ProtoReflect.Descriptor instead.
func (*Approval_Meta) Descriptor() ([]byte, []int) {
	return file_sym_messages_approval_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Approval_Meta) GetApprover() *models.User {
	if x != nil {
		return x.Approver
	}
	return nil
}

var File_sym_messages_approval_proto protoreflect.FileDescriptor

var file_sym_messages_approval_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x79, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x61,
	0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73,
	0x79, 0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x1a, 0x73, 0x79, 0x6d,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x73, 0x79, 0x6d, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x15, 0x73, 0x79, 0x6d, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x73, 0x79, 0x6d, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2f, 0x75, 0x75, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf0,
	0x01, 0x0a, 0x08, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x79, 0x6d, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a,
	0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x73, 0x79, 0x6d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x2f, 0x0a, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x79, 0x6d,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x04, 0x6d, 0x65,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x79, 0x6d, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x1a, 0x34, 0x0a, 0x04, 0x4d,
	0x65, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x79, 0x6d, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x08, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65,
	0x72, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x79, 0x6d, 0x6f, 0x70, 0x73, 0x69, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x67,
	0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_sym_messages_approval_proto_rawDescOnce sync.Once
	file_sym_messages_approval_proto_rawDescData = file_sym_messages_approval_proto_rawDesc
)

func file_sym_messages_approval_proto_rawDescGZIP() []byte {
	file_sym_messages_approval_proto_rawDescOnce.Do(func() {
		file_sym_messages_approval_proto_rawDescData = protoimpl.X.CompressGZIP(file_sym_messages_approval_proto_rawDescData)
	})
	return file_sym_messages_approval_proto_rawDescData
}

var file_sym_messages_approval_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sym_messages_approval_proto_goTypes = []interface{}{
	(*Approval)(nil),      // 0: sym.messages.Approval
	(*Approval_Meta)(nil), // 1: sym.messages.Approval.Meta
	(*models.UUID)(nil),   // 2: sym.models.UUID
	(*models.Schema)(nil), // 3: sym.models.Schema
	(*Request)(nil),       // 4: sym.messages.Request
	(*models.User)(nil),   // 5: sym.models.User
}
var file_sym_messages_approval_proto_depIdxs = []int32{
	2, // 0: sym.messages.Approval.id:type_name -> sym.models.UUID
	3, // 1: sym.messages.Approval.schema:type_name -> sym.models.Schema
	4, // 2: sym.messages.Approval.request:type_name -> sym.messages.Request
	1, // 3: sym.messages.Approval.meta:type_name -> sym.messages.Approval.Meta
	5, // 4: sym.messages.Approval.Meta.approver:type_name -> sym.models.User
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sym_messages_approval_proto_init() }
func file_sym_messages_approval_proto_init() {
	if File_sym_messages_approval_proto != nil {
		return
	}
	file_sym_messages_request_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_sym_messages_approval_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Approval); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sym_messages_approval_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Approval_Meta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sym_messages_approval_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sym_messages_approval_proto_goTypes,
		DependencyIndexes: file_sym_messages_approval_proto_depIdxs,
		MessageInfos:      file_sym_messages_approval_proto_msgTypes,
	}.Build()
	File_sym_messages_approval_proto = out.File
	file_sym_messages_approval_proto_rawDesc = nil
	file_sym_messages_approval_proto_goTypes = nil
	file_sym_messages_approval_proto_depIdxs = nil
}
