// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: sym/messages/expiration.proto

package messages

import (
	proto "github.com/golang/protobuf/proto"
	models "github.com/symopsio/types/go/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Expiration messages represent an approval that is now expired
type Expiration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *models.UUID       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Schema *models.Schema     `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Target *Expiration_Target `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *Expiration) Reset() {
	*x = Expiration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sym_messages_expiration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expiration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expiration) ProtoMessage() {}

func (x *Expiration) ProtoReflect() protoreflect.Message {
	mi := &file_sym_messages_expiration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expiration.ProtoReflect.Descriptor instead.
func (*Expiration) Descriptor() ([]byte, []int) {
	return file_sym_messages_expiration_proto_rawDescGZIP(), []int{0}
}

func (x *Expiration) GetId() *models.UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Expiration) GetSchema() *models.Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Expiration) GetTarget() *Expiration_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

type Expiration_Target struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User     *models.User     `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`         // user to remove access from
	Resource *models.Resource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"` // resource to remove access to
}

func (x *Expiration_Target) Reset() {
	*x = Expiration_Target{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sym_messages_expiration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expiration_Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expiration_Target) ProtoMessage() {}

func (x *Expiration_Target) ProtoReflect() protoreflect.Message {
	mi := &file_sym_messages_expiration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expiration_Target.ProtoReflect.Descriptor instead.
func (*Expiration_Target) Descriptor() ([]byte, []int) {
	return file_sym_messages_expiration_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Expiration_Target) GetUser() *models.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Expiration_Target) GetResource() *models.Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

var File_sym_messages_expiration_proto protoreflect.FileDescriptor

var file_sym_messages_expiration_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x79, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0c, 0x73, 0x79, 0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x19, 0x73,
	0x79, 0x6d, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x73, 0x79, 0x6d, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x15, 0x73, 0x79, 0x6d, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x73, 0x79, 0x6d, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2f, 0x75, 0x75, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xf5, 0x01, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x79, 0x6d,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x2a, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x73, 0x79, 0x6d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x53, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x37, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73,
	0x79, 0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x1a, 0x60, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12,
	0x24, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x73, 0x79, 0x6d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x79, 0x6d, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x6d, 0x6f, 0x70, 0x73, 0x69, 0x6f, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sym_messages_expiration_proto_rawDescOnce sync.Once
	file_sym_messages_expiration_proto_rawDescData = file_sym_messages_expiration_proto_rawDesc
)

func file_sym_messages_expiration_proto_rawDescGZIP() []byte {
	file_sym_messages_expiration_proto_rawDescOnce.Do(func() {
		file_sym_messages_expiration_proto_rawDescData = protoimpl.X.CompressGZIP(file_sym_messages_expiration_proto_rawDescData)
	})
	return file_sym_messages_expiration_proto_rawDescData
}

var file_sym_messages_expiration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sym_messages_expiration_proto_goTypes = []interface{}{
	(*Expiration)(nil),        // 0: sym.messages.Expiration
	(*Expiration_Target)(nil), // 1: sym.messages.Expiration.Target
	(*models.UUID)(nil),       // 2: sym.models.UUID
	(*models.Schema)(nil),     // 3: sym.models.Schema
	(*models.User)(nil),       // 4: sym.models.User
	(*models.Resource)(nil),   // 5: sym.models.Resource
}
var file_sym_messages_expiration_proto_depIdxs = []int32{
	2, // 0: sym.messages.Expiration.id:type_name -> sym.models.UUID
	3, // 1: sym.messages.Expiration.schema:type_name -> sym.models.Schema
	1, // 2: sym.messages.Expiration.target:type_name -> sym.messages.Expiration.Target
	4, // 3: sym.messages.Expiration.Target.user:type_name -> sym.models.User
	5, // 4: sym.messages.Expiration.Target.resource:type_name -> sym.models.Resource
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sym_messages_expiration_proto_init() }
func file_sym_messages_expiration_proto_init() {
	if File_sym_messages_expiration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sym_messages_expiration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Expiration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sym_messages_expiration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Expiration_Target); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sym_messages_expiration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sym_messages_expiration_proto_goTypes,
		DependencyIndexes: file_sym_messages_expiration_proto_depIdxs,
		MessageInfos:      file_sym_messages_expiration_proto_msgTypes,
	}.Build()
	File_sym_messages_expiration_proto = out.File
	file_sym_messages_expiration_proto_rawDesc = nil
	file_sym_messages_expiration_proto_goTypes = nil
	file_sym_messages_expiration_proto_depIdxs = nil
}
