// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: sym/messages/expiration.proto

package messages

import (
	proto "github.com/golang/protobuf/proto"
	models "github.com/symopsio/types/go/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Expiration messages represent an approval that is now expired
type Expiration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *models.UUID   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Schema   *models.Schema `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Approval *Approval      `protobuf:"bytes,3,opt,name=approval,proto3" json:"approval,omitempty"`
}

func (x *Expiration) Reset() {
	*x = Expiration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sym_messages_expiration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expiration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expiration) ProtoMessage() {}

func (x *Expiration) ProtoReflect() protoreflect.Message {
	mi := &file_sym_messages_expiration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expiration.ProtoReflect.Descriptor instead.
func (*Expiration) Descriptor() ([]byte, []int) {
	return file_sym_messages_expiration_proto_rawDescGZIP(), []int{0}
}

func (x *Expiration) GetId() *models.UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Expiration) GetSchema() *models.Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Expiration) GetApproval() *Approval {
	if x != nil {
		return x.Approval
	}
	return nil
}

var File_sym_messages_expiration_proto protoreflect.FileDescriptor

var file_sym_messages_expiration_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x79, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0c, 0x73, 0x79, 0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x17, 0x73,
	0x79, 0x6d, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x73, 0x79, 0x6d, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2f, 0x75, 0x75, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x73,
	0x79, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x72,
	0x6f, 0x76, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x01, 0x0a, 0x0a, 0x45,
	0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x79, 0x6d, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x06, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x79,
	0x6d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52,
	0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x32, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x79, 0x6d, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61,
	0x6c, 0x52, 0x08, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x42, 0x27, 0x5a, 0x25, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x6d, 0x6f, 0x70, 0x73,
	0x69, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sym_messages_expiration_proto_rawDescOnce sync.Once
	file_sym_messages_expiration_proto_rawDescData = file_sym_messages_expiration_proto_rawDesc
)

func file_sym_messages_expiration_proto_rawDescGZIP() []byte {
	file_sym_messages_expiration_proto_rawDescOnce.Do(func() {
		file_sym_messages_expiration_proto_rawDescData = protoimpl.X.CompressGZIP(file_sym_messages_expiration_proto_rawDescData)
	})
	return file_sym_messages_expiration_proto_rawDescData
}

var file_sym_messages_expiration_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sym_messages_expiration_proto_goTypes = []interface{}{
	(*Expiration)(nil),    // 0: sym.messages.Expiration
	(*models.UUID)(nil),   // 1: sym.models.UUID
	(*models.Schema)(nil), // 2: sym.models.Schema
	(*Approval)(nil),      // 3: sym.messages.Approval
}
var file_sym_messages_expiration_proto_depIdxs = []int32{
	1, // 0: sym.messages.Expiration.id:type_name -> sym.models.UUID
	2, // 1: sym.messages.Expiration.schema:type_name -> sym.models.Schema
	3, // 2: sym.messages.Expiration.approval:type_name -> sym.messages.Approval
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sym_messages_expiration_proto_init() }
func file_sym_messages_expiration_proto_init() {
	if File_sym_messages_expiration_proto != nil {
		return
	}
	file_sym_messages_approval_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_sym_messages_expiration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Expiration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sym_messages_expiration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sym_messages_expiration_proto_goTypes,
		DependencyIndexes: file_sym_messages_expiration_proto_depIdxs,
		MessageInfos:      file_sym_messages_expiration_proto_msgTypes,
	}.Build()
	File_sym_messages_expiration_proto = out.File
	file_sym_messages_expiration_proto_rawDesc = nil
	file_sym_messages_expiration_proto_goTypes = nil
	file_sym_messages_expiration_proto_depIdxs = nil
}
