// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: sym/messages/request.proto

package messages

import (
	proto "github.com/golang/protobuf/proto"
	models "github.com/symopsio/types/go/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Request represents some user request for access
type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *models.UUID    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Schema *models.Schema  `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Target *Request_Target `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"` // The target user and resource
	Meta   *Request_Meta   `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`     // Metadata about the request
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sym_messages_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_sym_messages_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_sym_messages_request_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetId() *models.UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Request) GetSchema() *models.Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Request) GetTarget() *Request_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Request) GetMeta() *Request_Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// Metadata about the request
type Request_Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"` // user-defined arbitrary reason
}

func (x *Request_Meta) Reset() {
	*x = Request_Meta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sym_messages_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_Meta) ProtoMessage() {}

func (x *Request_Meta) ProtoReflect() protoreflect.Message {
	mi := &file_sym_messages_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_Meta.ProtoReflect.Descriptor instead.
func (*Request_Meta) Descriptor() ([]byte, []int) {
	return file_sym_messages_request_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Request_Meta) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Target combines the requesting user and resource
type Request_Target struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User     *models.User     `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`         // user to grant access to
	Resource *models.Resource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"` // resource to give access to
}

func (x *Request_Target) Reset() {
	*x = Request_Target{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sym_messages_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_Target) ProtoMessage() {}

func (x *Request_Target) ProtoReflect() protoreflect.Message {
	mi := &file_sym_messages_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_Target.ProtoReflect.Descriptor instead.
func (*Request_Target) Descriptor() ([]byte, []int) {
	return file_sym_messages_request_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Request_Target) GetUser() *models.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Request_Target) GetResource() *models.Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

var File_sym_messages_request_proto protoreflect.FileDescriptor

var file_sym_messages_request_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x79, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x79,
	0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x19, 0x73, 0x79, 0x6d, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x73, 0x79, 0x6d, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15,
	0x73, 0x79, 0x6d, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x73, 0x79, 0x6d, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x75, 0x75, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbf, 0x02, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x79, 0x6d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x79, 0x6d,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x06,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x34, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x79, 0x6d, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x2e, 0x0a, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x79, 0x6d,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x1a, 0x1e, 0x0a, 0x04,
	0x4d, 0x65, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x1a, 0x60, 0x0a, 0x06,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x79, 0x6d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x73, 0x79, 0x6d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x27,
	0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x6d,
	0x6f, 0x70, 0x73, 0x69, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sym_messages_request_proto_rawDescOnce sync.Once
	file_sym_messages_request_proto_rawDescData = file_sym_messages_request_proto_rawDesc
)

func file_sym_messages_request_proto_rawDescGZIP() []byte {
	file_sym_messages_request_proto_rawDescOnce.Do(func() {
		file_sym_messages_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_sym_messages_request_proto_rawDescData)
	})
	return file_sym_messages_request_proto_rawDescData
}

var file_sym_messages_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sym_messages_request_proto_goTypes = []interface{}{
	(*Request)(nil),         // 0: sym.messages.Request
	(*Request_Meta)(nil),    // 1: sym.messages.Request.Meta
	(*Request_Target)(nil),  // 2: sym.messages.Request.Target
	(*models.UUID)(nil),     // 3: sym.models.UUID
	(*models.Schema)(nil),   // 4: sym.models.Schema
	(*models.User)(nil),     // 5: sym.models.User
	(*models.Resource)(nil), // 6: sym.models.Resource
}
var file_sym_messages_request_proto_depIdxs = []int32{
	3, // 0: sym.messages.Request.id:type_name -> sym.models.UUID
	4, // 1: sym.messages.Request.schema:type_name -> sym.models.Schema
	2, // 2: sym.messages.Request.target:type_name -> sym.messages.Request.Target
	1, // 3: sym.messages.Request.meta:type_name -> sym.messages.Request.Meta
	5, // 4: sym.messages.Request.Target.user:type_name -> sym.models.User
	6, // 5: sym.messages.Request.Target.resource:type_name -> sym.models.Resource
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sym_messages_request_proto_init() }
func file_sym_messages_request_proto_init() {
	if File_sym_messages_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sym_messages_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sym_messages_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_Meta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sym_messages_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_Target); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sym_messages_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sym_messages_request_proto_goTypes,
		DependencyIndexes: file_sym_messages_request_proto_depIdxs,
		MessageInfos:      file_sym_messages_request_proto_msgTypes,
	}.Build()
	File_sym_messages_request_proto = out.File
	file_sym_messages_request_proto_rawDesc = nil
	file_sym_messages_request_proto_goTypes = nil
	file_sym_messages_request_proto_depIdxs = nil
}
